default: &default
  adapter: postgresql
  encoding: unicode
  host: 13.235.133.213
  username: myuser
  password: mypassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_rails_app_development

test:
  <<: *default
  database: my_rails_app_test

production:
  <<: *default
  database: my_rails_app_production
  username: my_rails_app
  password: <%= ENV["MY_RAILS_APP_DATABASE_PASSWORD"] %>

external_database:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  host: 13.235.133.213
  username: myuser
  password: mypassword
  port: 5432 # Default PostgreSQL port, change if yours is different

