default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_SERVICE_HOST'] %>
  port: <%= ENV['POSTGRES_SERVICE_PORT'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_rails_app_development

test:
  <<: *default
  database: my_rails_app_test

production:
  <<: *default
  database: my_rails_app_production
  username: my_rails_app
  password: <%= ENV["MY_RAILS_APP_DATABASE_PASSWORD"] %>

external_database:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  host: <%= ENV['POSTGRES_SERVICE_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_SERVICE_PORT'] %>
