# rails-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: dev232/rails-app-final:latest
          env:
            - name: POSTGRES_SERVICE_HOST
              value: "postgres-service"
            - name: POSTGRES_SERVICE_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: REDIS_SERVICE_HOST
              value: "redis-cache"
            - name: REDIS_SERVICE_PORT
              value: "6379"
          ports:
            - containerPort: 3000



